### ISSUE TITLE
Why is it calling rebuild_course_cache

### ISSUE THREAD

**Issue by mudrd8mz** [blackbean/moodle-mod_vimeo#2]
Why is the module calling `rebuild_course_cache()` upon adding, updating or deleting an instance?

**Comment by brunomagalhaes** [comment]
Hi David,

Thank you for your help reviewing this plugin. 

Regarding your question, yes we had some cache issues not working correctly on the course main page when, for example, changing a video's description. We suspected at the time that was due to using the cached_cm_info class, but searching the forums we found this alternative solution. 

Best,
Bruno
